print("Hello! Hi! BYE! BYE!")
print("Welcome to Letter counter app")
name = input("Enter you name: ")
print("Hello "+name.capitalize())
print("The main goal in creating of this app is to count the number of times a desired letter occurs in the message.")
letter = input("Enter the letter you want to search for: ")
message = input("Enter the meassage in which you want to search: ")
letter = letter.lower()
message = message.lower()
letter_counter = message.count(letter)
print("The number of times "+letter+" occurs in the message is "+str(letter_counter))
